myboot.name=Spring 테스트환경

# log level - debug
logging.level.com.basic.admin=debug

# h2 DB
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
